
auth.token=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

defaults.org=personal-of4
defaults.project=ps_reactnative-fast_food

defaults.url=https://sentry.io/
