import {
  APPWRITE_ENDPOINT,
  APPWRITE_PLATFORM,
  APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_USER_TABLE_ID,
  APPWRITE_MENU_TABLE_ID,
  APPWRITE_CUSTOMIZATIONS_TABLE_ID,
  APPWRITE_MENU_CUSTOMIZATIONS_TABLE_ID,
  APPWRITE_BUCKET_ID,
  APPWRITE_CATEGORY_TABLE_ID,
  APPWRITE_API_KEY,
  APPWRITE_CART_TABLE_ID,
} from '@env';

export const appwriteConfig = {
  endpoint: APPWRITE_ENDPOINT,
  platform: APPWRITE_PLATFORM,
  projectId: APPWRITE_PROJECT_ID,
  databaseId: APPWRITE_DATABASE_ID,
  appwriteBucketId: APPWRITE_BUCKET_ID,
  appwriteApiKey: APPWRITE_API_KEY,

  usersCollectionId: APPWRITE_USER_TABLE_ID,
  categoriesCollectionId: APPWRITE_CATEGORY_TABLE_ID,
  menuCollectionId: APPWRITE_MENU_TABLE_ID,
  customizationsCollectionId: APPWRITE_CUSTOMIZATIONS_TABLE_ID,
  menuCustomizationsCollectionId: APPWRITE_MENU_CUSTOMIZATIONS_TABLE_ID,
  cartCollectionId: APPWRITE_CART_TABLE_ID,
};
